services:
  - type: web
    name: dadashboard
    env: static
    buildCommand: echo "Static site, no build command"
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html